// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/metadata/metadata.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PingConnectionRequest represents  ping connection request message.
type PingConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingConnectionRequest) Reset() {
	*x = PingConnectionRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingConnectionRequest) ProtoMessage() {}

func (x *PingConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingConnectionRequest.ProtoReflect.Descriptor instead.
func (*PingConnectionRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{0}
}

// PingConnectionResponse represents ping connection response message.
type PingConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingConnectionResponse) Reset() {
	*x = PingConnectionResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingConnectionResponse) ProtoMessage() {}

func (x *PingConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingConnectionResponse.ProtoReflect.Descriptor instead.
func (*PingConnectionResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *PingConnectionResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// Position represents common position message.
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int64                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int64                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_api_metadata_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *Position) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

// CreateSessionRequest represents create session request.
// User is allowed to create only 3 sessions in 10 minutes.
type CreateSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Represents an identifier of the user, which generated during
	// application installation.
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// CreateSessionResponse represents create session response.
type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSessionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// RemoveSessionRequest represents remove session request.
type RemoveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSessionRequest) Reset() {
	*x = RemoveSessionRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSessionRequest) ProtoMessage() {}

func (x *RemoveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSessionRequest.ProtoReflect.Descriptor instead.
func (*RemoveSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// RemoveSessionResponse represents remove session response.
type RemoveSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSessionResponse) Reset() {
	*x = RemoveSessionResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSessionResponse) ProtoMessage() {}

func (x *RemoveSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSessionResponse.ProtoReflect.Descriptor instead.
func (*RemoveSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{6}
}

// JoinToSessionRequest represents user join to session request.
type JoinToSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinToSessionRequest) Reset() {
	*x = JoinToSessionRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinToSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinToSessionRequest) ProtoMessage() {}

func (x *JoinToSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinToSessionRequest.ProtoReflect.Descriptor instead.
func (*JoinToSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{7}
}

func (x *JoinToSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *JoinToSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// JoinToSessionResponse represents user join to session response.
type JoinToSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinToSessionResponse) Reset() {
	*x = JoinToSessionResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinToSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinToSessionResponse) ProtoMessage() {}

func (x *JoinToSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinToSessionResponse.ProtoReflect.Descriptor instead.
func (*JoinToSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{8}
}

// Represents chests retrieval request message.
type GetChestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChestsRequest) Reset() {
	*x = GetChestsRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChestsRequest) ProtoMessage() {}

func (x *GetChestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChestsRequest.ProtoReflect.Descriptor instead.
func (*GetChestsRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{9}
}

// Represents chests retrieval response streaming message.
type GetChestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Position            `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChestsResponse) Reset() {
	*x = GetChestsResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChestsResponse) ProtoMessage() {}

func (x *GetChestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChestsResponse.ProtoReflect.Descriptor instead.
func (*GetChestsResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{10}
}

func (x *GetChestsResponse) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

// Represents map retrieval request message.
type GetMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapRequest) Reset() {
	*x = GetMapRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapRequest) ProtoMessage() {}

func (x *GetMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapRequest.ProtoReflect.Descriptor instead.
func (*GetMapRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{11}
}

// Represents map retrieval response streaming message.
type GetMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Position            `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapResponse) Reset() {
	*x = GetMapResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapResponse) ProtoMessage() {}

func (x *GetMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapResponse.ProtoReflect.Descriptor instead.
func (*GetMapResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{12}
}

func (x *GetMapResponse) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

// Represents chat retrieval request message.
type GetChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatRequest) Reset() {
	*x = GetChatRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatRequest) ProtoMessage() {}

func (x *GetChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatRequest.ProtoReflect.Descriptor instead.
func (*GetChatRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{13}
}

func (x *GetChatRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Represents chat retrieval response streaming message.
type GetChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []string               `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatResponse) Reset() {
	*x = GetChatResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatResponse) ProtoMessage() {}

func (x *GetChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatResponse.ProtoReflect.Descriptor instead.
func (*GetChatResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{14}
}

func (x *GetChatResponse) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_api_metadata_metadata_proto protoreflect.FileDescriptor

const file_api_metadata_metadata_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/metadata/metadata.proto\x12\bmetadata\"\x17\n" +
	"\x15PingConnectionRequest\"0\n" +
	"\x16PingConnectionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x03R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x03R\x01y\"C\n" +
	"\x14CreateSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"'\n" +
	"\x15CreateSessionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"&\n" +
	"\x14RemoveSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15RemoveSessionResponse\"N\n" +
	"\x14JoinToSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x17\n" +
	"\x15JoinToSessionResponse\"\x12\n" +
	"\x10GetChestsRequest\"E\n" +
	"\x11GetChestsResponse\x120\n" +
	"\tpositions\x18\x01 \x03(\v2\x12.metadata.PositionR\tpositions\"\x0f\n" +
	"\rGetMapRequest\"B\n" +
	"\x0eGetMapResponse\x120\n" +
	"\tpositions\x18\x01 \x03(\v2\x12.metadata.PositionR\tpositions\"(\n" +
	"\x0eGetChatRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\"-\n" +
	"\x0fGetChatResponse\x12\x1a\n" +
	"\bmessages\x18\x01 \x03(\tR\bmessages2\xaa\x04\n" +
	"\bMetadata\x12U\n" +
	"\x0ePingConnection\x12\x1f.metadata.PingConnectionRequest\x1a .metadata.PingConnectionResponse\"\x00\x12R\n" +
	"\rCreateSession\x12\x1e.metadata.CreateSessionRequest\x1a\x1f.metadata.CreateSessionResponse\"\x00\x12R\n" +
	"\rRemoveSession\x12\x1e.metadata.RemoveSessionRequest\x1a\x1f.metadata.RemoveSessionResponse\"\x00\x12R\n" +
	"\rJoinToSession\x12\x1e.metadata.JoinToSessionRequest\x1a\x1f.metadata.JoinToSessionResponse\"\x00\x12F\n" +
	"\tGetChests\x12\x1a.metadata.GetChestsRequest\x1a\x1b.metadata.GetChestsResponse\"\x00\x12?\n" +
	"\x06GetMap\x12\x17.metadata.GetMapRequest\x1a\x18.metadata.GetMapResponse\"\x000\x01\x12B\n" +
	"\aGetChat\x12\x18.metadata.GetChatRequest\x1a\x19.metadata.GetChatResponse\"\x000\x01BFZDgithub.com/YarikRevich/fate-seekers/pkg/core/networking/metadata/apib\x06proto3"

var (
	file_api_metadata_metadata_proto_rawDescOnce sync.Once
	file_api_metadata_metadata_proto_rawDescData []byte
)

func file_api_metadata_metadata_proto_rawDescGZIP() []byte {
	file_api_metadata_metadata_proto_rawDescOnce.Do(func() {
		file_api_metadata_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_metadata_metadata_proto_rawDesc), len(file_api_metadata_metadata_proto_rawDesc)))
	})
	return file_api_metadata_metadata_proto_rawDescData
}

var file_api_metadata_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_metadata_metadata_proto_goTypes = []any{
	(*PingConnectionRequest)(nil),  // 0: metadata.PingConnectionRequest
	(*PingConnectionResponse)(nil), // 1: metadata.PingConnectionResponse
	(*Position)(nil),               // 2: metadata.Position
	(*CreateSessionRequest)(nil),   // 3: metadata.CreateSessionRequest
	(*CreateSessionResponse)(nil),  // 4: metadata.CreateSessionResponse
	(*RemoveSessionRequest)(nil),   // 5: metadata.RemoveSessionRequest
	(*RemoveSessionResponse)(nil),  // 6: metadata.RemoveSessionResponse
	(*JoinToSessionRequest)(nil),   // 7: metadata.JoinToSessionRequest
	(*JoinToSessionResponse)(nil),  // 8: metadata.JoinToSessionResponse
	(*GetChestsRequest)(nil),       // 9: metadata.GetChestsRequest
	(*GetChestsResponse)(nil),      // 10: metadata.GetChestsResponse
	(*GetMapRequest)(nil),          // 11: metadata.GetMapRequest
	(*GetMapResponse)(nil),         // 12: metadata.GetMapResponse
	(*GetChatRequest)(nil),         // 13: metadata.GetChatRequest
	(*GetChatResponse)(nil),        // 14: metadata.GetChatResponse
}
var file_api_metadata_metadata_proto_depIdxs = []int32{
	2,  // 0: metadata.GetChestsResponse.positions:type_name -> metadata.Position
	2,  // 1: metadata.GetMapResponse.positions:type_name -> metadata.Position
	0,  // 2: metadata.Metadata.PingConnection:input_type -> metadata.PingConnectionRequest
	3,  // 3: metadata.Metadata.CreateSession:input_type -> metadata.CreateSessionRequest
	5,  // 4: metadata.Metadata.RemoveSession:input_type -> metadata.RemoveSessionRequest
	7,  // 5: metadata.Metadata.JoinToSession:input_type -> metadata.JoinToSessionRequest
	9,  // 6: metadata.Metadata.GetChests:input_type -> metadata.GetChestsRequest
	11, // 7: metadata.Metadata.GetMap:input_type -> metadata.GetMapRequest
	13, // 8: metadata.Metadata.GetChat:input_type -> metadata.GetChatRequest
	1,  // 9: metadata.Metadata.PingConnection:output_type -> metadata.PingConnectionResponse
	4,  // 10: metadata.Metadata.CreateSession:output_type -> metadata.CreateSessionResponse
	6,  // 11: metadata.Metadata.RemoveSession:output_type -> metadata.RemoveSessionResponse
	8,  // 12: metadata.Metadata.JoinToSession:output_type -> metadata.JoinToSessionResponse
	10, // 13: metadata.Metadata.GetChests:output_type -> metadata.GetChestsResponse
	12, // 14: metadata.Metadata.GetMap:output_type -> metadata.GetMapResponse
	14, // 15: metadata.Metadata.GetChat:output_type -> metadata.GetChatResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_metadata_metadata_proto_init() }
func file_api_metadata_metadata_proto_init() {
	if File_api_metadata_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_metadata_metadata_proto_rawDesc), len(file_api_metadata_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_metadata_metadata_proto_goTypes,
		DependencyIndexes: file_api_metadata_metadata_proto_depIdxs,
		MessageInfos:      file_api_metadata_metadata_proto_msgTypes,
	}.Build()
	File_api_metadata_metadata_proto = out.File
	file_api_metadata_metadata_proto_goTypes = nil
	file_api_metadata_metadata_proto_depIdxs = nil
}
