// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/metadata/metadata.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PingConnectionRequest represents  ping connection request message.
type PingConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingConnectionRequest) Reset() {
	*x = PingConnectionRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingConnectionRequest) ProtoMessage() {}

func (x *PingConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingConnectionRequest.ProtoReflect.Descriptor instead.
func (*PingConnectionRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *PingConnectionRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

// PingConnectionResponse represents ping connection response message.
type PingConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingConnectionResponse) Reset() {
	*x = PingConnectionResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingConnectionResponse) ProtoMessage() {}

func (x *PingConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingConnectionResponse.ProtoReflect.Descriptor instead.
func (*PingConnectionResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{1}
}

// GetSessionsRequest represents get sesssions request.
type GetSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionsRequest) Reset() {
	*x = GetSessionsRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionsRequest) ProtoMessage() {}

func (x *GetSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionsRequest.ProtoReflect.Descriptor instead.
func (*GetSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *GetSessionsRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

// Session represents common session retrieval message.
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_api_metadata_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *Session) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetSessionsResponse represents get sesssions response.
type GetSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionsResponse) Reset() {
	*x = GetSessionsResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionsResponse) ProtoMessage() {}

func (x *GetSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionsResponse.ProtoReflect.Descriptor instead.
func (*GetSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *GetSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// CreateSessionRequest represents create session request.
// User is allowed to create only 3 sessions in 10 minutes.
type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Seed          *int64                 `protobuf:"varint,3,opt,name=seed,proto3,oneof" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSessionRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *CreateSessionRequest) GetSeed() int64 {
	if x != nil && x.Seed != nil {
		return *x.Seed
	}
	return 0
}

// CreateSessionResponse represents create session response.
type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// RemoveSessionRequest represents remove session request.
type RemoveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSessionRequest) Reset() {
	*x = RemoveSessionRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSessionRequest) ProtoMessage() {}

func (x *RemoveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSessionRequest.ProtoReflect.Descriptor instead.
func (*RemoveSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// RemoveSessionResponse represents remove session response.
type RemoveSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSessionResponse) Reset() {
	*x = RemoveSessionResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSessionResponse) ProtoMessage() {}

func (x *RemoveSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSessionResponse.ProtoReflect.Descriptor instead.
func (*RemoveSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{8}
}

// JoinToSessionRequest represents user join to session request.
type JoinToSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinToSessionRequest) Reset() {
	*x = JoinToSessionRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinToSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinToSessionRequest) ProtoMessage() {}

func (x *JoinToSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinToSessionRequest.ProtoReflect.Descriptor instead.
func (*JoinToSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{9}
}

func (x *JoinToSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *JoinToSessionRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

// JoinToSessionResponse represents user join to session response.
type JoinToSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinToSessionResponse) Reset() {
	*x = JoinToSessionResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinToSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinToSessionResponse) ProtoMessage() {}

func (x *JoinToSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinToSessionResponse.ProtoReflect.Descriptor instead.
func (*JoinToSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{10}
}

// GetChestsRequest represents chests retrieval request message.
type GetChestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChestsRequest) Reset() {
	*x = GetChestsRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChestsRequest) ProtoMessage() {}

func (x *GetChestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChestsRequest.ProtoReflect.Descriptor instead.
func (*GetChestsRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{11}
}

func (x *GetChestsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Position represents common position message.
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int64                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int64                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_api_metadata_metadata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{12}
}

func (x *Position) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

// GetChestsResponse represents chests retrieval response streaming message.
type GetChestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Position            `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChestsResponse) Reset() {
	*x = GetChestsResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChestsResponse) ProtoMessage() {}

func (x *GetChestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChestsResponse.ProtoReflect.Descriptor instead.
func (*GetChestsResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{13}
}

func (x *GetChestsResponse) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

// GetMapRequest represents map retrieval request message.
type GetMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapRequest) Reset() {
	*x = GetMapRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapRequest) ProtoMessage() {}

func (x *GetMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapRequest.ProtoReflect.Descriptor instead.
func (*GetMapRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{14}
}

func (x *GetMapRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// GetMapResponse represents map retrieval response streaming message.
type GetMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Position            `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapResponse) Reset() {
	*x = GetMapResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapResponse) ProtoMessage() {}

func (x *GetMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapResponse.ProtoReflect.Descriptor instead.
func (*GetMapResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{15}
}

func (x *GetMapResponse) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

// GetChatRequest represents chat retrieval request message.
type GetChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatRequest) Reset() {
	*x = GetChatRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatRequest) ProtoMessage() {}

func (x *GetChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatRequest.ProtoReflect.Descriptor instead.
func (*GetChatRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{16}
}

func (x *GetChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetChatRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// ChatMessage represents common chat retrieval message.
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_api_metadata_metadata_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{17}
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// GetChatResponse represents chat retrieval response streaming message.
type GetChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []string               `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatResponse) Reset() {
	*x = GetChatResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatResponse) ProtoMessage() {}

func (x *GetChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatResponse.ProtoReflect.Descriptor instead.
func (*GetChatResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{18}
}

func (x *GetChatResponse) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

// CreateChatMessageRequest represents chat message creation request message.
type CreateChatMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatMessageRequest) Reset() {
	*x = CreateChatMessageRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatMessageRequest) ProtoMessage() {}

func (x *CreateChatMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateChatMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{19}
}

func (x *CreateChatMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateChatMessageRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// CreateChatMessageResponse represents chat message creation request message.
type CreateChatMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatMessageResponse) Reset() {
	*x = CreateChatMessageResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatMessageResponse) ProtoMessage() {}

func (x *CreateChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatMessageResponse.ProtoReflect.Descriptor instead.
func (*CreateChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{20}
}

var File_api_metadata_metadata_proto protoreflect.FileDescriptor

const file_api_metadata_metadata_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/metadata/metadata.proto\x12\bmetadata\x1a\x1fgoogle/protobuf/timestamp.proto\"/\n" +
	"\x15PingConnectionRequest\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\"\x18\n" +
	"\x16PingConnectionResponse\",\n" +
	"\x12GetSessionsRequest\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\"<\n" +
	"\aSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"D\n" +
	"\x13GetSessionsResponse\x12-\n" +
	"\bsessions\x18\x01 \x03(\v2\x11.metadata.SessionR\bsessions\"d\n" +
	"\x14CreateSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x17\n" +
	"\x04seed\x18\x03 \x01(\x03H\x00R\x04seed\x88\x01\x01B\a\n" +
	"\x05_seed\"6\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"5\n" +
	"\x14RemoveSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x17\n" +
	"\x15RemoveSessionResponse\"M\n" +
	"\x14JoinToSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\"\x17\n" +
	"\x15JoinToSessionResponse\"1\n" +
	"\x10GetChestsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x03R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x03R\x01y\"E\n" +
	"\x11GetChestsResponse\x120\n" +
	"\tpositions\x18\x01 \x03(\v2\x12.metadata.PositionR\tpositions\".\n" +
	"\rGetMapRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"B\n" +
	"\x0eGetMapResponse\x120\n" +
	"\tpositions\x18\x01 \x03(\v2\x12.metadata.PositionR\tpositions\"G\n" +
	"\x0eGetChatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"y\n" +
	"\vChatMessage\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"-\n" +
	"\x0fGetChatResponse\x12\x1a\n" +
	"\bmessages\x18\x01 \x03(\tR\bmessages\"Q\n" +
	"\x18CreateChatMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"\x1b\n" +
	"\x19CreateChatMessageResponse2\xd8\x05\n" +
	"\bMetadata\x12U\n" +
	"\x0ePingConnection\x12\x1f.metadata.PingConnectionRequest\x1a .metadata.PingConnectionResponse\"\x00\x12L\n" +
	"\vGetSessions\x12\x1c.metadata.GetSessionsRequest\x1a\x1d.metadata.GetSessionsResponse\"\x00\x12R\n" +
	"\rCreateSession\x12\x1e.metadata.CreateSessionRequest\x1a\x1f.metadata.CreateSessionResponse\"\x00\x12R\n" +
	"\rRemoveSession\x12\x1e.metadata.RemoveSessionRequest\x1a\x1f.metadata.RemoveSessionResponse\"\x00\x12R\n" +
	"\rJoinToSession\x12\x1e.metadata.JoinToSessionRequest\x1a\x1f.metadata.JoinToSessionResponse\"\x00\x12F\n" +
	"\tGetChests\x12\x1a.metadata.GetChestsRequest\x1a\x1b.metadata.GetChestsResponse\"\x00\x12?\n" +
	"\x06GetMap\x12\x17.metadata.GetMapRequest\x1a\x18.metadata.GetMapResponse\"\x000\x01\x12B\n" +
	"\aGetChat\x12\x18.metadata.GetChatRequest\x1a\x19.metadata.GetChatResponse\"\x000\x01\x12^\n" +
	"\x11CreateChatMessage\x12\".metadata.CreateChatMessageRequest\x1a#.metadata.CreateChatMessageResponse\"\x00BFZDgithub.com/YarikRevich/fate-seekers/pkg/core/networking/metadata/apib\x06proto3"

var (
	file_api_metadata_metadata_proto_rawDescOnce sync.Once
	file_api_metadata_metadata_proto_rawDescData []byte
)

func file_api_metadata_metadata_proto_rawDescGZIP() []byte {
	file_api_metadata_metadata_proto_rawDescOnce.Do(func() {
		file_api_metadata_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_metadata_metadata_proto_rawDesc), len(file_api_metadata_metadata_proto_rawDesc)))
	})
	return file_api_metadata_metadata_proto_rawDescData
}

var file_api_metadata_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_metadata_metadata_proto_goTypes = []any{
	(*PingConnectionRequest)(nil),     // 0: metadata.PingConnectionRequest
	(*PingConnectionResponse)(nil),    // 1: metadata.PingConnectionResponse
	(*GetSessionsRequest)(nil),        // 2: metadata.GetSessionsRequest
	(*Session)(nil),                   // 3: metadata.Session
	(*GetSessionsResponse)(nil),       // 4: metadata.GetSessionsResponse
	(*CreateSessionRequest)(nil),      // 5: metadata.CreateSessionRequest
	(*CreateSessionResponse)(nil),     // 6: metadata.CreateSessionResponse
	(*RemoveSessionRequest)(nil),      // 7: metadata.RemoveSessionRequest
	(*RemoveSessionResponse)(nil),     // 8: metadata.RemoveSessionResponse
	(*JoinToSessionRequest)(nil),      // 9: metadata.JoinToSessionRequest
	(*JoinToSessionResponse)(nil),     // 10: metadata.JoinToSessionResponse
	(*GetChestsRequest)(nil),          // 11: metadata.GetChestsRequest
	(*Position)(nil),                  // 12: metadata.Position
	(*GetChestsResponse)(nil),         // 13: metadata.GetChestsResponse
	(*GetMapRequest)(nil),             // 14: metadata.GetMapRequest
	(*GetMapResponse)(nil),            // 15: metadata.GetMapResponse
	(*GetChatRequest)(nil),            // 16: metadata.GetChatRequest
	(*ChatMessage)(nil),               // 17: metadata.ChatMessage
	(*GetChatResponse)(nil),           // 18: metadata.GetChatResponse
	(*CreateChatMessageRequest)(nil),  // 19: metadata.CreateChatMessageRequest
	(*CreateChatMessageResponse)(nil), // 20: metadata.CreateChatMessageResponse
	(*timestamppb.Timestamp)(nil),     // 21: google.protobuf.Timestamp
}
var file_api_metadata_metadata_proto_depIdxs = []int32{
	3,  // 0: metadata.GetSessionsResponse.sessions:type_name -> metadata.Session
	12, // 1: metadata.GetChestsResponse.positions:type_name -> metadata.Position
	12, // 2: metadata.GetMapResponse.positions:type_name -> metadata.Position
	21, // 3: metadata.ChatMessage.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 4: metadata.Metadata.PingConnection:input_type -> metadata.PingConnectionRequest
	2,  // 5: metadata.Metadata.GetSessions:input_type -> metadata.GetSessionsRequest
	5,  // 6: metadata.Metadata.CreateSession:input_type -> metadata.CreateSessionRequest
	7,  // 7: metadata.Metadata.RemoveSession:input_type -> metadata.RemoveSessionRequest
	9,  // 8: metadata.Metadata.JoinToSession:input_type -> metadata.JoinToSessionRequest
	11, // 9: metadata.Metadata.GetChests:input_type -> metadata.GetChestsRequest
	14, // 10: metadata.Metadata.GetMap:input_type -> metadata.GetMapRequest
	16, // 11: metadata.Metadata.GetChat:input_type -> metadata.GetChatRequest
	19, // 12: metadata.Metadata.CreateChatMessage:input_type -> metadata.CreateChatMessageRequest
	1,  // 13: metadata.Metadata.PingConnection:output_type -> metadata.PingConnectionResponse
	4,  // 14: metadata.Metadata.GetSessions:output_type -> metadata.GetSessionsResponse
	6,  // 15: metadata.Metadata.CreateSession:output_type -> metadata.CreateSessionResponse
	8,  // 16: metadata.Metadata.RemoveSession:output_type -> metadata.RemoveSessionResponse
	10, // 17: metadata.Metadata.JoinToSession:output_type -> metadata.JoinToSessionResponse
	13, // 18: metadata.Metadata.GetChests:output_type -> metadata.GetChestsResponse
	15, // 19: metadata.Metadata.GetMap:output_type -> metadata.GetMapResponse
	18, // 20: metadata.Metadata.GetChat:output_type -> metadata.GetChatResponse
	20, // 21: metadata.Metadata.CreateChatMessage:output_type -> metadata.CreateChatMessageResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_metadata_metadata_proto_init() }
func file_api_metadata_metadata_proto_init() {
	if File_api_metadata_metadata_proto != nil {
		return
	}
	file_api_metadata_metadata_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_metadata_metadata_proto_rawDesc), len(file_api_metadata_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_metadata_metadata_proto_goTypes,
		DependencyIndexes: file_api_metadata_metadata_proto_depIdxs,
		MessageInfos:      file_api_metadata_metadata_proto_msgTypes,
	}.Build()
	File_api_metadata_metadata_proto = out.File
	file_api_metadata_metadata_proto_goTypes = nil
	file_api_metadata_metadata_proto_depIdxs = nil
}
