// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/content/content.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PingConnectionRequest represents  ping connection request message.
type PingConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingConnectionRequest) Reset() {
	*x = PingConnectionRequest{}
	mi := &file_api_content_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingConnectionRequest) ProtoMessage() {}

func (x *PingConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingConnectionRequest.ProtoReflect.Descriptor instead.
func (*PingConnectionRequest) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{0}
}

func (x *PingConnectionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// PingConnectionResponse represents ping connection response message.
type PingConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingConnectionResponse) Reset() {
	*x = PingConnectionResponse{}
	mi := &file_api_content_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingConnectionResponse) ProtoMessage() {}

func (x *PingConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingConnectionResponse.ProtoReflect.Descriptor instead.
func (*PingConnectionResponse) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{1}
}

func (x *PingConnectionResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// Represents common position message.
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int64                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int64                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_api_content_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{2}
}

func (x *Position) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Represents users positions retrieval request message.
type GetUserPositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPositionsRequest) Reset() {
	*x = GetUserPositionsRequest{}
	mi := &file_api_content_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPositionsRequest) ProtoMessage() {}

func (x *GetUserPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPositionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPositionsRequest) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserPositionsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Represents users positions retrieval response message.
type GetUserPositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Position            `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPositionsResponse) Reset() {
	*x = GetUserPositionsResponse{}
	mi := &file_api_content_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPositionsResponse) ProtoMessage() {}

func (x *GetUserPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPositionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPositionsResponse) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserPositionsResponse) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

var File_api_content_content_proto protoreflect.FileDescriptor

const file_api_content_content_proto_rawDesc = "" +
	"\n" +
	"\x19api/content/content.proto\x12\acontent\"-\n" +
	"\x15PingConnectionRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"0\n" +
	"\x16PingConnectionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x03R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x03R\x01y\"/\n" +
	"\x17GetUserPositionsRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"K\n" +
	"\x18GetUserPositionsResponse\x12/\n" +
	"\tpositions\x18\x01 \x03(\v2\x11.content.PositionR\tpositions2\xb7\x01\n" +
	"\aContent\x12S\n" +
	"\x0ePingConnection\x12\x1e.content.PingConnectionRequest\x1a\x1f.content.PingConnectionResponse\"\x00\x12W\n" +
	"\x10GetUserPositions\x12 .content.GetUserPositionsRequest\x1a!.content.GetUserPositionsResponseBEZCgithub.com/YarikRevich/fate-seekers/pkg/core/networking/content/apib\x06proto3"

var (
	file_api_content_content_proto_rawDescOnce sync.Once
	file_api_content_content_proto_rawDescData []byte
)

func file_api_content_content_proto_rawDescGZIP() []byte {
	file_api_content_content_proto_rawDescOnce.Do(func() {
		file_api_content_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_content_content_proto_rawDesc), len(file_api_content_content_proto_rawDesc)))
	})
	return file_api_content_content_proto_rawDescData
}

var file_api_content_content_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_content_content_proto_goTypes = []any{
	(*PingConnectionRequest)(nil),    // 0: content.PingConnectionRequest
	(*PingConnectionResponse)(nil),   // 1: content.PingConnectionResponse
	(*Position)(nil),                 // 2: content.Position
	(*GetUserPositionsRequest)(nil),  // 3: content.GetUserPositionsRequest
	(*GetUserPositionsResponse)(nil), // 4: content.GetUserPositionsResponse
}
var file_api_content_content_proto_depIdxs = []int32{
	2, // 0: content.GetUserPositionsResponse.positions:type_name -> content.Position
	0, // 1: content.Content.PingConnection:input_type -> content.PingConnectionRequest
	3, // 2: content.Content.GetUserPositions:input_type -> content.GetUserPositionsRequest
	1, // 3: content.Content.PingConnection:output_type -> content.PingConnectionResponse
	4, // 4: content.Content.GetUserPositions:output_type -> content.GetUserPositionsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_content_content_proto_init() }
func file_api_content_content_proto_init() {
	if File_api_content_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_content_content_proto_rawDesc), len(file_api_content_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_content_content_proto_goTypes,
		DependencyIndexes: file_api_content_content_proto_depIdxs,
		MessageInfos:      file_api_content_content_proto_msgTypes,
	}.Build()
	File_api_content_content_proto = out.File
	file_api_content_content_proto_goTypes = nil
	file_api_content_content_proto_depIdxs = nil
}
