// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: metadata/v1/metadata.proto

package metadatav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetadataService_PingConnection_FullMethodName        = "/metadata.v1.MetadataService/PingConnection"
	MetadataService_UpdateSessionActivity_FullMethodName = "/metadata.v1.MetadataService/UpdateSessionActivity"
	MetadataService_CreateUserIfNotExists_FullMethodName = "/metadata.v1.MetadataService/CreateUserIfNotExists"
	MetadataService_GetUserSessions_FullMethodName       = "/metadata.v1.MetadataService/GetUserSessions"
	MetadataService_GetFilteredSession_FullMethodName    = "/metadata.v1.MetadataService/GetFilteredSession"
	MetadataService_CreateSession_FullMethodName         = "/metadata.v1.MetadataService/CreateSession"
	MetadataService_RemoveSession_FullMethodName         = "/metadata.v1.MetadataService/RemoveSession"
	MetadataService_StartSession_FullMethodName          = "/metadata.v1.MetadataService/StartSession"
	MetadataService_GetSessionMetadata_FullMethodName    = "/metadata.v1.MetadataService/GetSessionMetadata"
	MetadataService_GetLobbySet_FullMethodName           = "/metadata.v1.MetadataService/GetLobbySet"
	MetadataService_CreateLobby_FullMethodName           = "/metadata.v1.MetadataService/CreateLobby"
	MetadataService_RemoveLobby_FullMethodName           = "/metadata.v1.MetadataService/RemoveLobby"
	MetadataService_LeaveLobby_FullMethodName            = "/metadata.v1.MetadataService/LeaveLobby"
	MetadataService_GetUsersMetadata_FullMethodName      = "/metadata.v1.MetadataService/GetUsersMetadata"
	MetadataService_DropInventoryItem_FullMethodName     = "/metadata.v1.MetadataService/DropInventoryItem"
	MetadataService_TakeChestItem_FullMethodName         = "/metadata.v1.MetadataService/TakeChestItem"
	MetadataService_OpenChest_FullMethodName             = "/metadata.v1.MetadataService/OpenChest"
	MetadataService_GetChests_FullMethodName             = "/metadata.v1.MetadataService/GetChests"
	MetadataService_OpenHealthPack_FullMethodName        = "/metadata.v1.MetadataService/OpenHealthPack"
	MetadataService_GetHealthPacks_FullMethodName        = "/metadata.v1.MetadataService/GetHealthPacks"
	MetadataService_GetEvents_FullMethodName             = "/metadata.v1.MetadataService/GetEvents"
)

// MetadataServiceClient is the client API for MetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Represents service used to retrieve user content related data.
// All the metadata requests require authentication header to be provided, having JWT token saved in it.
type MetadataServiceClient interface {
	// PingConnection performs ping connection and creates user record on the server side at the same time,
	// if such does not exist.
	PingConnection(ctx context.Context, in *PingConnectionRequest, opts ...grpc.CallOption) (*PingConnectionResponse, error)
	// UpdateSessionActivity performs session activity update.
	UpdateSessionActivity(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UpdateSessionActivityRequest, UpdateSessionActivityResponse], error)
	// CreateUserIfNotExists performs attempt to create a user, if it hasn't been create yet.
	CreateUserIfNotExists(ctx context.Context, in *CreateUserIfNotExistsRequest, opts ...grpc.CallOption) (*CreateUserIfNotExistsResponse, error)
	// GetUserSessions performs existing sessions retrieval operation by the configured user.
	GetUserSessions(ctx context.Context, in *GetUserSessionsRequest, opts ...grpc.CallOption) (*GetUserSessionsResponse, error)
	// GetFilteredSession performs existing filtered session retrieval operation by the configured user.
	GetFilteredSession(ctx context.Context, in *GetFilteredSessionRequest, opts ...grpc.CallOption) (*GetFilteredSessionResponse, error)
	// CreateSession performs session creation operation by the configured user.
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	// RemoveSession performs session removal operation by the configured user. Allowed for session owner only.
	RemoveSession(ctx context.Context, in *RemoveSessionRequest, opts ...grpc.CallOption) (*RemoveSessionResponse, error)
	// StartSession performs start session operation by the configured user. Allowed for session host only.
	StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error)
	// GetSessionMetadata performs session metadata retrieval request by the configured user.
	GetSessionMetadata(ctx context.Context, in *GetSessionMetadataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetSessionMetadataResponse], error)
	// GetLobbySet performs existing lobbies retrieval operation by the provided session id, by the configured user.
	GetLobbySet(ctx context.Context, in *GetLobbySetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetLobbySetResponse], error)
	// CreateLobby performs lobby creation operation by the configured user.
	CreateLobby(ctx context.Context, in *CreateLobbyRequest, opts ...grpc.CallOption) (*CreateLobbyResponse, error)
	// RemoveLobby performs lobby removal operation by the configured user. Allowed for lobby owner only.
	RemoveLobby(ctx context.Context, in *RemoveLobbyRequest, opts ...grpc.CallOption) (*RemoveLobbyResponse, error)
	// LeaveLobby performs lobby leave operation by the configured user.
	LeaveLobby(ctx context.Context, in *LeaveLobbyRequest, opts ...grpc.CallOption) (*LeaveLobbyResponse, error)
	// GetUsersMetadata performs users metadata retrieval request by the configured user.
	GetUsersMetadata(ctx context.Context, in *GetUsersMetadataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetUsersMetadataResponse], error)
	// DropInventoryItem performs inventory item drop request by the configured user.
	DropInventoryItem(ctx context.Context, in *DropInventoryItemRequest, opts ...grpc.CallOption) (*DropInventoryItemResponse, error)
	// TakeChestItem performs chest item take operaiton for the selected chest by the configured user.
	TakeChestItem(ctx context.Context, in *TakeChestItemRequest, opts ...grpc.CallOption) (*TakeChestItemResponse, error)
	// OpenChest performs chest open operation for the selected chest by the configured user.
	OpenChest(ctx context.Context, in *OpenChestRequest, opts ...grpc.CallOption) (*OpenChestResponse, error)
	// GetChests performs chests retrieval for the selected session by the configured user.
	GetChests(ctx context.Context, in *GetChestsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetChestsResponse], error)
	// OpenHealthPack performs health pack open operation for the selected health pack by the configured user.
	OpenHealthPack(ctx context.Context, in *OpenHealthPackRequest, opts ...grpc.CallOption) (*OpenHealthPackResponse, error)
	// GetHealthPacks performs health packs retrieval for the selected session by the configured user.
	GetHealthPacks(ctx context.Context, in *GetHealthPacksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetHealthPacksResponse], error)
	// GetEvents performs weather events retrieval for the selected session by the configured user.
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetEventsResponse], error)
}

type metadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataServiceClient(cc grpc.ClientConnInterface) MetadataServiceClient {
	return &metadataServiceClient{cc}
}

func (c *metadataServiceClient) PingConnection(ctx context.Context, in *PingConnectionRequest, opts ...grpc.CallOption) (*PingConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingConnectionResponse)
	err := c.cc.Invoke(ctx, MetadataService_PingConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) UpdateSessionActivity(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UpdateSessionActivityRequest, UpdateSessionActivityResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetadataService_ServiceDesc.Streams[0], MetadataService_UpdateSessionActivity_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpdateSessionActivityRequest, UpdateSessionActivityResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetadataService_UpdateSessionActivityClient = grpc.ClientStreamingClient[UpdateSessionActivityRequest, UpdateSessionActivityResponse]

func (c *metadataServiceClient) CreateUserIfNotExists(ctx context.Context, in *CreateUserIfNotExistsRequest, opts ...grpc.CallOption) (*CreateUserIfNotExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserIfNotExistsResponse)
	err := c.cc.Invoke(ctx, MetadataService_CreateUserIfNotExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetUserSessions(ctx context.Context, in *GetUserSessionsRequest, opts ...grpc.CallOption) (*GetUserSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserSessionsResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetUserSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetFilteredSession(ctx context.Context, in *GetFilteredSessionRequest, opts ...grpc.CallOption) (*GetFilteredSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFilteredSessionResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetFilteredSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, MetadataService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) RemoveSession(ctx context.Context, in *RemoveSessionRequest, opts ...grpc.CallOption) (*RemoveSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveSessionResponse)
	err := c.cc.Invoke(ctx, MetadataService_RemoveSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSessionResponse)
	err := c.cc.Invoke(ctx, MetadataService_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetSessionMetadata(ctx context.Context, in *GetSessionMetadataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetSessionMetadataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetadataService_ServiceDesc.Streams[1], MetadataService_GetSessionMetadata_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetSessionMetadataRequest, GetSessionMetadataResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetadataService_GetSessionMetadataClient = grpc.ServerStreamingClient[GetSessionMetadataResponse]

func (c *metadataServiceClient) GetLobbySet(ctx context.Context, in *GetLobbySetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetLobbySetResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetadataService_ServiceDesc.Streams[2], MetadataService_GetLobbySet_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetLobbySetRequest, GetLobbySetResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetadataService_GetLobbySetClient = grpc.ServerStreamingClient[GetLobbySetResponse]

func (c *metadataServiceClient) CreateLobby(ctx context.Context, in *CreateLobbyRequest, opts ...grpc.CallOption) (*CreateLobbyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLobbyResponse)
	err := c.cc.Invoke(ctx, MetadataService_CreateLobby_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) RemoveLobby(ctx context.Context, in *RemoveLobbyRequest, opts ...grpc.CallOption) (*RemoveLobbyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveLobbyResponse)
	err := c.cc.Invoke(ctx, MetadataService_RemoveLobby_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) LeaveLobby(ctx context.Context, in *LeaveLobbyRequest, opts ...grpc.CallOption) (*LeaveLobbyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveLobbyResponse)
	err := c.cc.Invoke(ctx, MetadataService_LeaveLobby_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetUsersMetadata(ctx context.Context, in *GetUsersMetadataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetUsersMetadataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetadataService_ServiceDesc.Streams[3], MetadataService_GetUsersMetadata_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetUsersMetadataRequest, GetUsersMetadataResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetadataService_GetUsersMetadataClient = grpc.ServerStreamingClient[GetUsersMetadataResponse]

func (c *metadataServiceClient) DropInventoryItem(ctx context.Context, in *DropInventoryItemRequest, opts ...grpc.CallOption) (*DropInventoryItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropInventoryItemResponse)
	err := c.cc.Invoke(ctx, MetadataService_DropInventoryItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) TakeChestItem(ctx context.Context, in *TakeChestItemRequest, opts ...grpc.CallOption) (*TakeChestItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TakeChestItemResponse)
	err := c.cc.Invoke(ctx, MetadataService_TakeChestItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) OpenChest(ctx context.Context, in *OpenChestRequest, opts ...grpc.CallOption) (*OpenChestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenChestResponse)
	err := c.cc.Invoke(ctx, MetadataService_OpenChest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetChests(ctx context.Context, in *GetChestsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetChestsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetadataService_ServiceDesc.Streams[4], MetadataService_GetChests_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetChestsRequest, GetChestsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetadataService_GetChestsClient = grpc.ServerStreamingClient[GetChestsResponse]

func (c *metadataServiceClient) OpenHealthPack(ctx context.Context, in *OpenHealthPackRequest, opts ...grpc.CallOption) (*OpenHealthPackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenHealthPackResponse)
	err := c.cc.Invoke(ctx, MetadataService_OpenHealthPack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetHealthPacks(ctx context.Context, in *GetHealthPacksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetHealthPacksResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetadataService_ServiceDesc.Streams[5], MetadataService_GetHealthPacks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetHealthPacksRequest, GetHealthPacksResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetadataService_GetHealthPacksClient = grpc.ServerStreamingClient[GetHealthPacksResponse]

func (c *metadataServiceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetadataService_ServiceDesc.Streams[6], MetadataService_GetEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetEventsRequest, GetEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetadataService_GetEventsClient = grpc.ServerStreamingClient[GetEventsResponse]

// MetadataServiceServer is the server API for MetadataService service.
// All implementations must embed UnimplementedMetadataServiceServer
// for forward compatibility.
//
// Represents service used to retrieve user content related data.
// All the metadata requests require authentication header to be provided, having JWT token saved in it.
type MetadataServiceServer interface {
	// PingConnection performs ping connection and creates user record on the server side at the same time,
	// if such does not exist.
	PingConnection(context.Context, *PingConnectionRequest) (*PingConnectionResponse, error)
	// UpdateSessionActivity performs session activity update.
	UpdateSessionActivity(grpc.ClientStreamingServer[UpdateSessionActivityRequest, UpdateSessionActivityResponse]) error
	// CreateUserIfNotExists performs attempt to create a user, if it hasn't been create yet.
	CreateUserIfNotExists(context.Context, *CreateUserIfNotExistsRequest) (*CreateUserIfNotExistsResponse, error)
	// GetUserSessions performs existing sessions retrieval operation by the configured user.
	GetUserSessions(context.Context, *GetUserSessionsRequest) (*GetUserSessionsResponse, error)
	// GetFilteredSession performs existing filtered session retrieval operation by the configured user.
	GetFilteredSession(context.Context, *GetFilteredSessionRequest) (*GetFilteredSessionResponse, error)
	// CreateSession performs session creation operation by the configured user.
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	// RemoveSession performs session removal operation by the configured user. Allowed for session owner only.
	RemoveSession(context.Context, *RemoveSessionRequest) (*RemoveSessionResponse, error)
	// StartSession performs start session operation by the configured user. Allowed for session host only.
	StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error)
	// GetSessionMetadata performs session metadata retrieval request by the configured user.
	GetSessionMetadata(*GetSessionMetadataRequest, grpc.ServerStreamingServer[GetSessionMetadataResponse]) error
	// GetLobbySet performs existing lobbies retrieval operation by the provided session id, by the configured user.
	GetLobbySet(*GetLobbySetRequest, grpc.ServerStreamingServer[GetLobbySetResponse]) error
	// CreateLobby performs lobby creation operation by the configured user.
	CreateLobby(context.Context, *CreateLobbyRequest) (*CreateLobbyResponse, error)
	// RemoveLobby performs lobby removal operation by the configured user. Allowed for lobby owner only.
	RemoveLobby(context.Context, *RemoveLobbyRequest) (*RemoveLobbyResponse, error)
	// LeaveLobby performs lobby leave operation by the configured user.
	LeaveLobby(context.Context, *LeaveLobbyRequest) (*LeaveLobbyResponse, error)
	// GetUsersMetadata performs users metadata retrieval request by the configured user.
	GetUsersMetadata(*GetUsersMetadataRequest, grpc.ServerStreamingServer[GetUsersMetadataResponse]) error
	// DropInventoryItem performs inventory item drop request by the configured user.
	DropInventoryItem(context.Context, *DropInventoryItemRequest) (*DropInventoryItemResponse, error)
	// TakeChestItem performs chest item take operaiton for the selected chest by the configured user.
	TakeChestItem(context.Context, *TakeChestItemRequest) (*TakeChestItemResponse, error)
	// OpenChest performs chest open operation for the selected chest by the configured user.
	OpenChest(context.Context, *OpenChestRequest) (*OpenChestResponse, error)
	// GetChests performs chests retrieval for the selected session by the configured user.
	GetChests(*GetChestsRequest, grpc.ServerStreamingServer[GetChestsResponse]) error
	// OpenHealthPack performs health pack open operation for the selected health pack by the configured user.
	OpenHealthPack(context.Context, *OpenHealthPackRequest) (*OpenHealthPackResponse, error)
	// GetHealthPacks performs health packs retrieval for the selected session by the configured user.
	GetHealthPacks(*GetHealthPacksRequest, grpc.ServerStreamingServer[GetHealthPacksResponse]) error
	// GetEvents performs weather events retrieval for the selected session by the configured user.
	GetEvents(*GetEventsRequest, grpc.ServerStreamingServer[GetEventsResponse]) error
	mustEmbedUnimplementedMetadataServiceServer()
}

// UnimplementedMetadataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetadataServiceServer struct{}

func (UnimplementedMetadataServiceServer) PingConnection(context.Context, *PingConnectionRequest) (*PingConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingConnection not implemented")
}
func (UnimplementedMetadataServiceServer) UpdateSessionActivity(grpc.ClientStreamingServer[UpdateSessionActivityRequest, UpdateSessionActivityResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UpdateSessionActivity not implemented")
}
func (UnimplementedMetadataServiceServer) CreateUserIfNotExists(context.Context, *CreateUserIfNotExistsRequest) (*CreateUserIfNotExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserIfNotExists not implemented")
}
func (UnimplementedMetadataServiceServer) GetUserSessions(context.Context, *GetUserSessionsRequest) (*GetUserSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserSessions not implemented")
}
func (UnimplementedMetadataServiceServer) GetFilteredSession(context.Context, *GetFilteredSessionRequest) (*GetFilteredSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFilteredSession not implemented")
}
func (UnimplementedMetadataServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedMetadataServiceServer) RemoveSession(context.Context, *RemoveSessionRequest) (*RemoveSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSession not implemented")
}
func (UnimplementedMetadataServiceServer) StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedMetadataServiceServer) GetSessionMetadata(*GetSessionMetadataRequest, grpc.ServerStreamingServer[GetSessionMetadataResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetSessionMetadata not implemented")
}
func (UnimplementedMetadataServiceServer) GetLobbySet(*GetLobbySetRequest, grpc.ServerStreamingServer[GetLobbySetResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetLobbySet not implemented")
}
func (UnimplementedMetadataServiceServer) CreateLobby(context.Context, *CreateLobbyRequest) (*CreateLobbyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLobby not implemented")
}
func (UnimplementedMetadataServiceServer) RemoveLobby(context.Context, *RemoveLobbyRequest) (*RemoveLobbyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveLobby not implemented")
}
func (UnimplementedMetadataServiceServer) LeaveLobby(context.Context, *LeaveLobbyRequest) (*LeaveLobbyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveLobby not implemented")
}
func (UnimplementedMetadataServiceServer) GetUsersMetadata(*GetUsersMetadataRequest, grpc.ServerStreamingServer[GetUsersMetadataResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetUsersMetadata not implemented")
}
func (UnimplementedMetadataServiceServer) DropInventoryItem(context.Context, *DropInventoryItemRequest) (*DropInventoryItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropInventoryItem not implemented")
}
func (UnimplementedMetadataServiceServer) TakeChestItem(context.Context, *TakeChestItemRequest) (*TakeChestItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TakeChestItem not implemented")
}
func (UnimplementedMetadataServiceServer) OpenChest(context.Context, *OpenChestRequest) (*OpenChestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenChest not implemented")
}
func (UnimplementedMetadataServiceServer) GetChests(*GetChestsRequest, grpc.ServerStreamingServer[GetChestsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetChests not implemented")
}
func (UnimplementedMetadataServiceServer) OpenHealthPack(context.Context, *OpenHealthPackRequest) (*OpenHealthPackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenHealthPack not implemented")
}
func (UnimplementedMetadataServiceServer) GetHealthPacks(*GetHealthPacksRequest, grpc.ServerStreamingServer[GetHealthPacksResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetHealthPacks not implemented")
}
func (UnimplementedMetadataServiceServer) GetEvents(*GetEventsRequest, grpc.ServerStreamingServer[GetEventsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedMetadataServiceServer) mustEmbedUnimplementedMetadataServiceServer() {}
func (UnimplementedMetadataServiceServer) testEmbeddedByValue()                         {}

// UnsafeMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataServiceServer will
// result in compilation errors.
type UnsafeMetadataServiceServer interface {
	mustEmbedUnimplementedMetadataServiceServer()
}

func RegisterMetadataServiceServer(s grpc.ServiceRegistrar, srv MetadataServiceServer) {
	// If the following call pancis, it indicates UnimplementedMetadataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetadataService_ServiceDesc, srv)
}

func _MetadataService_PingConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).PingConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_PingConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).PingConnection(ctx, req.(*PingConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_UpdateSessionActivity_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetadataServiceServer).UpdateSessionActivity(&grpc.GenericServerStream[UpdateSessionActivityRequest, UpdateSessionActivityResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetadataService_UpdateSessionActivityServer = grpc.ClientStreamingServer[UpdateSessionActivityRequest, UpdateSessionActivityResponse]

func _MetadataService_CreateUserIfNotExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserIfNotExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).CreateUserIfNotExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_CreateUserIfNotExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).CreateUserIfNotExists(ctx, req.(*CreateUserIfNotExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetUserSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetUserSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetUserSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetUserSessions(ctx, req.(*GetUserSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetFilteredSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilteredSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetFilteredSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetFilteredSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetFilteredSession(ctx, req.(*GetFilteredSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_RemoveSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).RemoveSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_RemoveSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).RemoveSession(ctx, req.(*RemoveSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).StartSession(ctx, req.(*StartSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetSessionMetadata_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSessionMetadataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetadataServiceServer).GetSessionMetadata(m, &grpc.GenericServerStream[GetSessionMetadataRequest, GetSessionMetadataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetadataService_GetSessionMetadataServer = grpc.ServerStreamingServer[GetSessionMetadataResponse]

func _MetadataService_GetLobbySet_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLobbySetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetadataServiceServer).GetLobbySet(m, &grpc.GenericServerStream[GetLobbySetRequest, GetLobbySetResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetadataService_GetLobbySetServer = grpc.ServerStreamingServer[GetLobbySetResponse]

func _MetadataService_CreateLobby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLobbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).CreateLobby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_CreateLobby_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).CreateLobby(ctx, req.(*CreateLobbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_RemoveLobby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveLobbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).RemoveLobby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_RemoveLobby_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).RemoveLobby(ctx, req.(*RemoveLobbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_LeaveLobby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveLobbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).LeaveLobby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_LeaveLobby_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).LeaveLobby(ctx, req.(*LeaveLobbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetUsersMetadata_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetUsersMetadataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetadataServiceServer).GetUsersMetadata(m, &grpc.GenericServerStream[GetUsersMetadataRequest, GetUsersMetadataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetadataService_GetUsersMetadataServer = grpc.ServerStreamingServer[GetUsersMetadataResponse]

func _MetadataService_DropInventoryItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropInventoryItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).DropInventoryItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_DropInventoryItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).DropInventoryItem(ctx, req.(*DropInventoryItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_TakeChestItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakeChestItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).TakeChestItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_TakeChestItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).TakeChestItem(ctx, req.(*TakeChestItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_OpenChest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenChestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).OpenChest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_OpenChest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).OpenChest(ctx, req.(*OpenChestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetChests_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetChestsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetadataServiceServer).GetChests(m, &grpc.GenericServerStream[GetChestsRequest, GetChestsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetadataService_GetChestsServer = grpc.ServerStreamingServer[GetChestsResponse]

func _MetadataService_OpenHealthPack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenHealthPackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).OpenHealthPack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_OpenHealthPack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).OpenHealthPack(ctx, req.(*OpenHealthPackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetHealthPacks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetHealthPacksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetadataServiceServer).GetHealthPacks(m, &grpc.GenericServerStream[GetHealthPacksRequest, GetHealthPacksResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetadataService_GetHealthPacksServer = grpc.ServerStreamingServer[GetHealthPacksResponse]

func _MetadataService_GetEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetadataServiceServer).GetEvents(m, &grpc.GenericServerStream[GetEventsRequest, GetEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetadataService_GetEventsServer = grpc.ServerStreamingServer[GetEventsResponse]

// MetadataService_ServiceDesc is the grpc.ServiceDesc for MetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metadata.v1.MetadataService",
	HandlerType: (*MetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingConnection",
			Handler:    _MetadataService_PingConnection_Handler,
		},
		{
			MethodName: "CreateUserIfNotExists",
			Handler:    _MetadataService_CreateUserIfNotExists_Handler,
		},
		{
			MethodName: "GetUserSessions",
			Handler:    _MetadataService_GetUserSessions_Handler,
		},
		{
			MethodName: "GetFilteredSession",
			Handler:    _MetadataService_GetFilteredSession_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _MetadataService_CreateSession_Handler,
		},
		{
			MethodName: "RemoveSession",
			Handler:    _MetadataService_RemoveSession_Handler,
		},
		{
			MethodName: "StartSession",
			Handler:    _MetadataService_StartSession_Handler,
		},
		{
			MethodName: "CreateLobby",
			Handler:    _MetadataService_CreateLobby_Handler,
		},
		{
			MethodName: "RemoveLobby",
			Handler:    _MetadataService_RemoveLobby_Handler,
		},
		{
			MethodName: "LeaveLobby",
			Handler:    _MetadataService_LeaveLobby_Handler,
		},
		{
			MethodName: "DropInventoryItem",
			Handler:    _MetadataService_DropInventoryItem_Handler,
		},
		{
			MethodName: "TakeChestItem",
			Handler:    _MetadataService_TakeChestItem_Handler,
		},
		{
			MethodName: "OpenChest",
			Handler:    _MetadataService_OpenChest_Handler,
		},
		{
			MethodName: "OpenHealthPack",
			Handler:    _MetadataService_OpenHealthPack_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UpdateSessionActivity",
			Handler:       _MetadataService_UpdateSessionActivity_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetSessionMetadata",
			Handler:       _MetadataService_GetSessionMetadata_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetLobbySet",
			Handler:       _MetadataService_GetLobbySet_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetUsersMetadata",
			Handler:       _MetadataService_GetUsersMetadata_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetChests",
			Handler:       _MetadataService_GetChests_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetHealthPacks",
			Handler:       _MetadataService_GetHealthPacks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetEvents",
			Handler:       _MetadataService_GetEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "metadata/v1/metadata.proto",
}
