// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/metadata/metadata.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PingConnectionRequest represents  ping connection request message.
type PingConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingConnectionRequest) Reset() {
	*x = PingConnectionRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingConnectionRequest) ProtoMessage() {}

func (x *PingConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingConnectionRequest.ProtoReflect.Descriptor instead.
func (*PingConnectionRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *PingConnectionRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

// PingConnectionResponse represents ping connection response message.
type PingConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingConnectionResponse) Reset() {
	*x = PingConnectionResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingConnectionResponse) ProtoMessage() {}

func (x *PingConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingConnectionResponse.ProtoReflect.Descriptor instead.
func (*PingConnectionResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{1}
}

// GetSessionsRequest represents get sesssions request.
type GetSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionsRequest) Reset() {
	*x = GetSessionsRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionsRequest) ProtoMessage() {}

func (x *GetSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionsRequest.ProtoReflect.Descriptor instead.
func (*GetSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *GetSessionsRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

// Session represents common session retrieval message.
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Seed          int64                  `protobuf:"varint,2,opt,name=seed,proto3" json:"seed,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_api_metadata_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *Session) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *Session) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetSessionsResponse represents get sesssions response.
type GetSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionsResponse) Reset() {
	*x = GetSessionsResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionsResponse) ProtoMessage() {}

func (x *GetSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionsResponse.ProtoReflect.Descriptor instead.
func (*GetSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *GetSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// CreateSessionRequest represents create session request.
// User is allowed to create only 3 sessions in 10 minutes.
type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Seed          *int64                 `protobuf:"varint,3,opt,name=seed,proto3,oneof" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSessionRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *CreateSessionRequest) GetSeed() int64 {
	if x != nil && x.Seed != nil {
		return *x.Seed
	}
	return 0
}

// CreateSessionResponse represents create session response.
type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSessionResponse) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

// RemoveSessionRequest represents remove session request.
type RemoveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSessionRequest) Reset() {
	*x = RemoveSessionRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSessionRequest) ProtoMessage() {}

func (x *RemoveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSessionRequest.ProtoReflect.Descriptor instead.
func (*RemoveSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveSessionRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

// RemoveSessionResponse represents remove session response.
type RemoveSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSessionResponse) Reset() {
	*x = RemoveSessionResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSessionResponse) ProtoMessage() {}

func (x *RemoveSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSessionResponse.ProtoReflect.Descriptor instead.
func (*RemoveSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{8}
}

// GetLobbySetRequest represents user create lobby request.
type GetLobbySetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLobbySetRequest) Reset() {
	*x = GetLobbySetRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLobbySetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLobbySetRequest) ProtoMessage() {}

func (x *GetLobbySetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLobbySetRequest.ProtoReflect.Descriptor instead.
func (*GetLobbySetRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{9}
}

func (x *GetLobbySetRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *GetLobbySetRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

// GetLobbySetResponse represents user create lobby response.
type GetLobbySetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuers       []string               `protobuf:"bytes,1,rep,name=issuers,proto3" json:"issuers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLobbySetResponse) Reset() {
	*x = GetLobbySetResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLobbySetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLobbySetResponse) ProtoMessage() {}

func (x *GetLobbySetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLobbySetResponse.ProtoReflect.Descriptor instead.
func (*GetLobbySetResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{10}
}

func (x *GetLobbySetResponse) GetIssuers() []string {
	if x != nil {
		return x.Issuers
	}
	return nil
}

// CreateLobbyRequest represents user create lobby request.
type CreateLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLobbyRequest) Reset() {
	*x = CreateLobbyRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyRequest) ProtoMessage() {}

func (x *CreateLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyRequest.ProtoReflect.Descriptor instead.
func (*CreateLobbyRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{11}
}

func (x *CreateLobbyRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *CreateLobbyRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

// CreateLobbyResponse represents user create lobby response.
type CreateLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLobbyResponse) Reset() {
	*x = CreateLobbyResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyResponse) ProtoMessage() {}

func (x *CreateLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyResponse.ProtoReflect.Descriptor instead.
func (*CreateLobbyResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{12}
}

// RemoveLobbyRequest represents user remove lobby request.
type RemoveLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveLobbyRequest) Reset() {
	*x = RemoveLobbyRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveLobbyRequest) ProtoMessage() {}

func (x *RemoveLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveLobbyRequest.ProtoReflect.Descriptor instead.
func (*RemoveLobbyRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveLobbyRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

// RemoveLobbyResponse represents user remove lobby response.
type RemoveLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveLobbyResponse) Reset() {
	*x = RemoveLobbyResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveLobbyResponse) ProtoMessage() {}

func (x *RemoveLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveLobbyResponse.ProtoReflect.Descriptor instead.
func (*RemoveLobbyResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{14}
}

// Represents users metadata retrieval request message.
type GetUserMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserMetadataRequest) Reset() {
	*x = GetUserMetadataRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMetadataRequest) ProtoMessage() {}

func (x *GetUserMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetUserMetadataRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserMetadataRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *GetUserMetadataRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

// Represents common user metadata message.
type UserMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        int64                  `protobuf:"varint,1,opt,name=health,proto3" json:"health,omitempty"`
	Skin          int64                  `protobuf:"varint,2,opt,name=skin,proto3" json:"skin,omitempty"`
	Eliminated    bool                   `protobuf:"varint,3,opt,name=eliminated,proto3" json:"eliminated,omitempty"`
	Position      *Position              `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMetadata) Reset() {
	*x = UserMetadata{}
	mi := &file_api_metadata_metadata_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMetadata) ProtoMessage() {}

func (x *UserMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMetadata.ProtoReflect.Descriptor instead.
func (*UserMetadata) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{16}
}

func (x *UserMetadata) GetHealth() int64 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *UserMetadata) GetSkin() int64 {
	if x != nil {
		return x.Skin
	}
	return 0
}

func (x *UserMetadata) GetEliminated() bool {
	if x != nil {
		return x.Eliminated
	}
	return false
}

func (x *UserMetadata) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

// Represents users metadata retrieval response message.
type GetUserMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserMetadata  *UserMetadata          `protobuf:"bytes,1,opt,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserMetadataResponse) Reset() {
	*x = GetUserMetadataResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMetadataResponse) ProtoMessage() {}

func (x *GetUserMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetUserMetadataResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserMetadataResponse) GetUserMetadata() *UserMetadata {
	if x != nil {
		return x.UserMetadata
	}
	return nil
}

// GetChestsRequest represents chests retrieval request message.
type GetChestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChestsRequest) Reset() {
	*x = GetChestsRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChestsRequest) ProtoMessage() {}

func (x *GetChestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChestsRequest.ProtoReflect.Descriptor instead.
func (*GetChestsRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{18}
}

func (x *GetChestsRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

// Position represents common position message.
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_api_metadata_metadata_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{19}
}

func (x *Position) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

// GetChestsResponse represents chests retrieval response streaming message.
type GetChestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Position            `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChestsResponse) Reset() {
	*x = GetChestsResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChestsResponse) ProtoMessage() {}

func (x *GetChestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChestsResponse.ProtoReflect.Descriptor instead.
func (*GetChestsResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{20}
}

func (x *GetChestsResponse) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

// GetMapRequest represents map retrieval request message.
type GetMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapRequest) Reset() {
	*x = GetMapRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapRequest) ProtoMessage() {}

func (x *GetMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapRequest.ProtoReflect.Descriptor instead.
func (*GetMapRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{21}
}

func (x *GetMapRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

// GetMapResponse represents map retrieval response streaming message.
type GetMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Position            `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapResponse) Reset() {
	*x = GetMapResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapResponse) ProtoMessage() {}

func (x *GetMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapResponse.ProtoReflect.Descriptor instead.
func (*GetMapResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{22}
}

func (x *GetMapResponse) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

// GetChatMessagesRequest represents chat messages retrieval request message.
type GetChatMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatMessagesRequest) Reset() {
	*x = GetChatMessagesRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMessagesRequest) ProtoMessage() {}

func (x *GetChatMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetChatMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{23}
}

func (x *GetChatMessagesRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *GetChatMessagesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// ChatMessage represents common chat retrieval message.
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_api_metadata_metadata_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{24}
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// GetChatMessagesResponse represents chat messages retrieval response streaming message.
type GetChatMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatMessagesResponse) Reset() {
	*x = GetChatMessagesResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMessagesResponse) ProtoMessage() {}

func (x *GetChatMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetChatMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{25}
}

func (x *GetChatMessagesResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// CreateChatMessageRequest represents chat message creation request message.
type CreateChatMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatMessageRequest) Reset() {
	*x = CreateChatMessageRequest{}
	mi := &file_api_metadata_metadata_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatMessageRequest) ProtoMessage() {}

func (x *CreateChatMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateChatMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{26}
}

func (x *CreateChatMessageRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *CreateChatMessageRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// CreateChatMessageResponse represents chat message creation request message.
type CreateChatMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatMessageResponse) Reset() {
	*x = CreateChatMessageResponse{}
	mi := &file_api_metadata_metadata_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatMessageResponse) ProtoMessage() {}

func (x *CreateChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metadata_metadata_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatMessageResponse.ProtoReflect.Descriptor instead.
func (*CreateChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_metadata_metadata_proto_rawDescGZIP(), []int{27}
}

var File_api_metadata_metadata_proto protoreflect.FileDescriptor

const file_api_metadata_metadata_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/metadata/metadata.proto\x12\bmetadata\x1a\x1fgoogle/protobuf/timestamp.proto\"/\n" +
	"\x15PingConnectionRequest\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\"\x18\n" +
	"\x16PingConnectionResponse\",\n" +
	"\x12GetSessionsRequest\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\"P\n" +
	"\aSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x12\n" +
	"\x04seed\x18\x02 \x01(\x03R\x04seed\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"D\n" +
	"\x13GetSessionsResponse\x12-\n" +
	"\bsessions\x18\x01 \x03(\v2\x11.metadata.SessionR\bsessions\"d\n" +
	"\x14CreateSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x17\n" +
	"\x04seed\x18\x03 \x01(\x03H\x00R\x04seed\x88\x01\x01B\a\n" +
	"\x05_seed\"6\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\"5\n" +
	"\x14RemoveSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\"\x17\n" +
	"\x15RemoveSessionResponse\"K\n" +
	"\x12GetLobbySetRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\"/\n" +
	"\x13GetLobbySetResponse\x12\x18\n" +
	"\aissuers\x18\x01 \x03(\tR\aissuers\"K\n" +
	"\x12CreateLobbyRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\"\x15\n" +
	"\x13CreateLobbyResponse\",\n" +
	"\x12RemoveLobbyRequest\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\"\x15\n" +
	"\x13RemoveLobbyResponse\"O\n" +
	"\x16GetUserMetadataRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\"\x8a\x01\n" +
	"\fUserMetadata\x12\x16\n" +
	"\x06health\x18\x01 \x01(\x03R\x06health\x12\x12\n" +
	"\x04skin\x18\x02 \x01(\x03R\x04skin\x12\x1e\n" +
	"\n" +
	"eliminated\x18\x03 \x01(\bR\n" +
	"eliminated\x12.\n" +
	"\bposition\x18\x04 \x01(\v2\x12.metadata.PositionR\bposition\"V\n" +
	"\x17GetUserMetadataResponse\x12;\n" +
	"\ruser_metadata\x18\x01 \x01(\v2\x16.metadata.UserMetadataR\fuserMetadata\"1\n" +
	"\x10GetChestsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"E\n" +
	"\x11GetChestsResponse\x120\n" +
	"\tpositions\x18\x01 \x03(\v2\x12.metadata.PositionR\tpositions\".\n" +
	"\rGetMapRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\"B\n" +
	"\x0eGetMapResponse\x120\n" +
	"\tpositions\x18\x01 \x03(\v2\x12.metadata.PositionR\tpositions\"O\n" +
	"\x16GetChatMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"y\n" +
	"\vChatMessage\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"L\n" +
	"\x17GetChatMessagesResponse\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.metadata.ChatMessageR\bmessages\"Q\n" +
	"\x18CreateChatMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"\x1b\n" +
	"\x19CreateChatMessageResponse2\xe0\a\n" +
	"\bMetadata\x12U\n" +
	"\x0ePingConnection\x12\x1f.metadata.PingConnectionRequest\x1a .metadata.PingConnectionResponse\"\x00\x12L\n" +
	"\vGetSessions\x12\x1c.metadata.GetSessionsRequest\x1a\x1d.metadata.GetSessionsResponse\"\x00\x12R\n" +
	"\rCreateSession\x12\x1e.metadata.CreateSessionRequest\x1a\x1f.metadata.CreateSessionResponse\"\x00\x12R\n" +
	"\rRemoveSession\x12\x1e.metadata.RemoveSessionRequest\x1a\x1f.metadata.RemoveSessionResponse\"\x00\x12L\n" +
	"\vGetLobbySet\x12\x1c.metadata.GetLobbySetRequest\x1a\x1d.metadata.GetLobbySetResponse\"\x00\x12L\n" +
	"\vCreateLobby\x12\x1c.metadata.CreateLobbyRequest\x1a\x1d.metadata.CreateLobbyResponse\"\x00\x12L\n" +
	"\vRemoveLobby\x12\x1c.metadata.RemoveLobbyRequest\x1a\x1d.metadata.RemoveLobbyResponse\"\x00\x12X\n" +
	"\x0fGetUserMetadata\x12 .metadata.GetUserMetadataRequest\x1a!.metadata.GetUserMetadataResponse\"\x00\x12F\n" +
	"\tGetChests\x12\x1a.metadata.GetChestsRequest\x1a\x1b.metadata.GetChestsResponse\"\x00\x12?\n" +
	"\x06GetMap\x12\x17.metadata.GetMapRequest\x1a\x18.metadata.GetMapResponse\"\x000\x01\x12Z\n" +
	"\x0fGetChatMessages\x12 .metadata.GetChatMessagesRequest\x1a!.metadata.GetChatMessagesResponse\"\x000\x01\x12^\n" +
	"\x11CreateChatMessage\x12\".metadata.CreateChatMessageRequest\x1a#.metadata.CreateChatMessageResponse\"\x00BFZDgithub.com/YarikRevich/fate-seekers/pkg/core/networking/metadata/apib\x06proto3"

var (
	file_api_metadata_metadata_proto_rawDescOnce sync.Once
	file_api_metadata_metadata_proto_rawDescData []byte
)

func file_api_metadata_metadata_proto_rawDescGZIP() []byte {
	file_api_metadata_metadata_proto_rawDescOnce.Do(func() {
		file_api_metadata_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_metadata_metadata_proto_rawDesc), len(file_api_metadata_metadata_proto_rawDesc)))
	})
	return file_api_metadata_metadata_proto_rawDescData
}

var file_api_metadata_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_api_metadata_metadata_proto_goTypes = []any{
	(*PingConnectionRequest)(nil),     // 0: metadata.PingConnectionRequest
	(*PingConnectionResponse)(nil),    // 1: metadata.PingConnectionResponse
	(*GetSessionsRequest)(nil),        // 2: metadata.GetSessionsRequest
	(*Session)(nil),                   // 3: metadata.Session
	(*GetSessionsResponse)(nil),       // 4: metadata.GetSessionsResponse
	(*CreateSessionRequest)(nil),      // 5: metadata.CreateSessionRequest
	(*CreateSessionResponse)(nil),     // 6: metadata.CreateSessionResponse
	(*RemoveSessionRequest)(nil),      // 7: metadata.RemoveSessionRequest
	(*RemoveSessionResponse)(nil),     // 8: metadata.RemoveSessionResponse
	(*GetLobbySetRequest)(nil),        // 9: metadata.GetLobbySetRequest
	(*GetLobbySetResponse)(nil),       // 10: metadata.GetLobbySetResponse
	(*CreateLobbyRequest)(nil),        // 11: metadata.CreateLobbyRequest
	(*CreateLobbyResponse)(nil),       // 12: metadata.CreateLobbyResponse
	(*RemoveLobbyRequest)(nil),        // 13: metadata.RemoveLobbyRequest
	(*RemoveLobbyResponse)(nil),       // 14: metadata.RemoveLobbyResponse
	(*GetUserMetadataRequest)(nil),    // 15: metadata.GetUserMetadataRequest
	(*UserMetadata)(nil),              // 16: metadata.UserMetadata
	(*GetUserMetadataResponse)(nil),   // 17: metadata.GetUserMetadataResponse
	(*GetChestsRequest)(nil),          // 18: metadata.GetChestsRequest
	(*Position)(nil),                  // 19: metadata.Position
	(*GetChestsResponse)(nil),         // 20: metadata.GetChestsResponse
	(*GetMapRequest)(nil),             // 21: metadata.GetMapRequest
	(*GetMapResponse)(nil),            // 22: metadata.GetMapResponse
	(*GetChatMessagesRequest)(nil),    // 23: metadata.GetChatMessagesRequest
	(*ChatMessage)(nil),               // 24: metadata.ChatMessage
	(*GetChatMessagesResponse)(nil),   // 25: metadata.GetChatMessagesResponse
	(*CreateChatMessageRequest)(nil),  // 26: metadata.CreateChatMessageRequest
	(*CreateChatMessageResponse)(nil), // 27: metadata.CreateChatMessageResponse
	(*timestamppb.Timestamp)(nil),     // 28: google.protobuf.Timestamp
}
var file_api_metadata_metadata_proto_depIdxs = []int32{
	3,  // 0: metadata.GetSessionsResponse.sessions:type_name -> metadata.Session
	19, // 1: metadata.UserMetadata.position:type_name -> metadata.Position
	16, // 2: metadata.GetUserMetadataResponse.user_metadata:type_name -> metadata.UserMetadata
	19, // 3: metadata.GetChestsResponse.positions:type_name -> metadata.Position
	19, // 4: metadata.GetMapResponse.positions:type_name -> metadata.Position
	28, // 5: metadata.ChatMessage.timestamp:type_name -> google.protobuf.Timestamp
	24, // 6: metadata.GetChatMessagesResponse.messages:type_name -> metadata.ChatMessage
	0,  // 7: metadata.Metadata.PingConnection:input_type -> metadata.PingConnectionRequest
	2,  // 8: metadata.Metadata.GetSessions:input_type -> metadata.GetSessionsRequest
	5,  // 9: metadata.Metadata.CreateSession:input_type -> metadata.CreateSessionRequest
	7,  // 10: metadata.Metadata.RemoveSession:input_type -> metadata.RemoveSessionRequest
	9,  // 11: metadata.Metadata.GetLobbySet:input_type -> metadata.GetLobbySetRequest
	11, // 12: metadata.Metadata.CreateLobby:input_type -> metadata.CreateLobbyRequest
	13, // 13: metadata.Metadata.RemoveLobby:input_type -> metadata.RemoveLobbyRequest
	15, // 14: metadata.Metadata.GetUserMetadata:input_type -> metadata.GetUserMetadataRequest
	18, // 15: metadata.Metadata.GetChests:input_type -> metadata.GetChestsRequest
	21, // 16: metadata.Metadata.GetMap:input_type -> metadata.GetMapRequest
	23, // 17: metadata.Metadata.GetChatMessages:input_type -> metadata.GetChatMessagesRequest
	26, // 18: metadata.Metadata.CreateChatMessage:input_type -> metadata.CreateChatMessageRequest
	1,  // 19: metadata.Metadata.PingConnection:output_type -> metadata.PingConnectionResponse
	4,  // 20: metadata.Metadata.GetSessions:output_type -> metadata.GetSessionsResponse
	6,  // 21: metadata.Metadata.CreateSession:output_type -> metadata.CreateSessionResponse
	8,  // 22: metadata.Metadata.RemoveSession:output_type -> metadata.RemoveSessionResponse
	10, // 23: metadata.Metadata.GetLobbySet:output_type -> metadata.GetLobbySetResponse
	12, // 24: metadata.Metadata.CreateLobby:output_type -> metadata.CreateLobbyResponse
	14, // 25: metadata.Metadata.RemoveLobby:output_type -> metadata.RemoveLobbyResponse
	17, // 26: metadata.Metadata.GetUserMetadata:output_type -> metadata.GetUserMetadataResponse
	20, // 27: metadata.Metadata.GetChests:output_type -> metadata.GetChestsResponse
	22, // 28: metadata.Metadata.GetMap:output_type -> metadata.GetMapResponse
	25, // 29: metadata.Metadata.GetChatMessages:output_type -> metadata.GetChatMessagesResponse
	27, // 30: metadata.Metadata.CreateChatMessage:output_type -> metadata.CreateChatMessageResponse
	19, // [19:31] is the sub-list for method output_type
	7,  // [7:19] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_metadata_metadata_proto_init() }
func file_api_metadata_metadata_proto_init() {
	if File_api_metadata_metadata_proto != nil {
		return
	}
	file_api_metadata_metadata_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_metadata_metadata_proto_rawDesc), len(file_api_metadata_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_metadata_metadata_proto_goTypes,
		DependencyIndexes: file_api_metadata_metadata_proto_depIdxs,
		MessageInfos:      file_api_metadata_metadata_proto_msgTypes,
	}.Build()
	File_api_metadata_metadata_proto = out.File
	file_api_metadata_metadata_proto_goTypes = nil
	file_api_metadata_metadata_proto_depIdxs = nil
}
