window:
  height: 1080
  width: 1920

operation:
  debug: true

database:
  name: "fate_seekers.db"
  connection-retry-delay: 3s

logging:
  level: "debug"
  console: true
  name: "fate_seekers.log"
  directory: "log"