package value

import (
	"time"

	"github.com/YarikRevich/fate-seekers/services/fate-seekers-client/pkg/dto"
)

// Describes all the available screen reducer store values.
const (
	// Entry screen is expected to be used for initialization operations.
	ACTIVE_SCREEN_ENTRY_VALUE = "entry"

	ACTIVE_SCREEN_MENU_VALUE         = "menu"
	ACTIVE_SCREEN_CREDITS_VALUE      = "credits"
	ACTIVE_SCREEN_COLLECTIONS_VALUE  = "collections"
	ACTIVE_SCREEN_SETTINGS_VALUE     = "settings"
	ACTIVE_SCREEN_SELECTOR_VALUE     = "selector"
	ACTIVE_SCREEN_CREATOR_VALUE      = "creator"
	ACTIVE_SCREEN_LOBBY_VALUE        = "lobby"
	ACTIVE_SCREEN_SESSION_VALUE      = "session"
	ACTIVE_SCREEN_TRAVEL_VALUE       = "travel"
	ACTIVE_SCREEN_ANSWER_INPUT_VALUE = "answer_input"
	ACTIVE_SCREEN_RESUME_VALUE       = "resume"
	ACTIVE_SCREEN_DEATH_VALUE        = "death"

	PREVIOUS_SCREEN_MENU_VALUE   = "menu"
	PREVIOUS_SCREEN_RESUME_VALUE = "resume"
	PREVIOUS_SCREEN_EMPTY_VALUE  = ""
)

// Describes all the available application reducer store values.
const (
	EXIT_APPLICATION_FALSE_VALUE = "false"
	EXIT_APPLICATION_TRUE_VALUE  = "true"

	LOADING_APPLICATION_EMPTY_VALUE = 0

	STATE_RESET_APPLICATION_TRUE_VALUE  = "true"
	STATE_RESET_APPLICATION_FALSE_VALUE = "false"

	GAMEPAD_ENABLED_APPLICATION_TRUE_VALUE  = "true"
	GAMEPAD_ENABLED_APPLICATION_FALSE_VALUE = "false"
)

var (
	GAMEPAD_USAGE_APPLICATION_DEFAULT_VALUE time.Time
)

// Describes all the available repository reducer store values.
const (
	UUID_REPOSITORY_EMPTY_VALUE = ""

	UUID_CHECKED_REPOSITORY_TRUE_VALUE  = "true"
	UUID_CHECKED_REPOSITORY_FALSE_VALUE = "false"
)

// Describes all the available networking reducer store values.
const (
	ENTRY_HANDSHAKE_STARTED_NETWORKING_TRUE_VALUE  = "true"
	ENTRY_HANDSHAKE_STARTED_NETWORKING_FALSE_VALUE = "false"

	PING_CONNECTION_STARTED_NETWORKING_TRUE_VALUE  = "true"
	PING_CONNECTION_STARTED_NETWORKING_FALSE_VALUE = "false"

	SESSION_RETRIEVAL_STARTED_NETWORKING_TRUE_VALUE  = "true"
	SESSION_RETRIEVAL_STARTED_NETWORKING_FALSE_VALUE = "false"

	SESSION_CREATION_STARTED_NETWORKING_TRUE_VALUE  = "true"
	SESSION_CREATION_STARTED_NETWORKING_FALSE_VALUE = "false"

	SESSION_REMOVAL_STARTED_NETWORKING_TRUE_VALUE  = "true"
	SESSION_REMOVAL_STARTED_NETWORKING_FALSE_VALUE = "false"

	LOBBY_SET_RETRIEVAL_STARTED_NETWORKING_TRUE_VALUE  = "true"
	LOBBY_SET_RETRIEVAL_STARTED_NETWORKING_FALSE_VALUE = "false"

	LOBBY_SET_RETRIEVAL_CYCLE_FINISHED_NETWORKING_TRUE_VALUE  = "true"
	LOBBY_SET_RETRIEVAL_CYCLE_FINISHED_NETWORKING_FALSE_VALUE = "false"

	LOBBY_CREATION_STARTED_NETWORKING_TRUE_VALUE  = "true"
	LOBBY_CREATION_STARTED_NETWORKING_FALSE_VALUE = "false"

	LOBBY_REMOVAL_STARTED_NETWORKING_TRUE_VALUE  = "true"
	LOBBY_REMOVAL_STARTED_NETWORKING_FALSE_VALUE = "false"

	SESSION_METADATA_RETRIEVAL_STARTED_NETWORKING_TRUE_VALUE  = "true"
	SESSION_METADATA_RETRIEVAL_STARTED_NETWORKING_FALSE_VALUE = "false"

	UPDATE_USER_METADATA_POSITIONS_STARTED_NETWORKING_TRUE_VALUE  = "true"
	UPDATE_USER_METADATA_POSITIONS_STARTED_NETWORKING_FALSE_VALUE = "false"

	EVENT_RETRIEVAL_STARTED_NETWORKING_TRUE_STATE  = "true"
	EVENT_RETRIEVAL_STARTED_NETWORKING_FALSE_STATE = "false"

	USERS_METADATA_RETRIEVAL_STARTED_NETWORKING_TRUE_STATE  = "true"
	USERS_METADATA_RETRIEVAL_STARTED_NETWORKING_FALSE_STATE = "false"

	CHESTS_RETRIEVAL_STARTED_NETWORKING_TRUE_STATE  = "true"
	CHESTS_RETRIEVAL_STARTED_NETWORKING_FALSE_STATE = "false"

	HEALTH_PACKS_RETRIEVAL_STARTED_NETWORKING_TRUE_STATE  = "true"
	HEALTH_PACKS_RETRIEVAL_STARTED_NETWORKING_FALSE_STATE = "false"

	HIT_PLAYER_WITH_FIST_STARTED_NETWORKING_TRUE_STATE  = "true"
	HIT_PLAYER_WITH_FIST_STARTED_NETWORKING_FALSE_STATE = "false"
)

// Describes all the available letter reducer store values.
const (
	LETTER_UPDATED_TRUE_VALUE  = "true"
	LETTER_UPDATED_FALSE_VALUE = "false"
	LETTER_NAME_EMPTY_VALUE    = ""
	LETTER_IMAGE_EMPTY_VALUE   = ""
)

// Describes all the available answer input reducer store values.
const (
	ANSWER_INPUT_QUESTION_UPDATED_TRUE_VALUE  = "true"
	ANSWER_INPUT_QUESTION_UPDATED_FALSE_VALUE = "false"
)

// Describes available prompt reducer store values.
const (
	UPDATED_PROMPT_TRUE_VALUE  = "true"
	UPDATED_PROMPT_FALSE_VALUE = "false"
	TEXT_PROMPT_EMPTY_VALUE    = ""
)

// Describes available prompt reducer store values.
var (
	SUBMIT_PROMPT_CALLBACK_EMPTY_VALUE = func() {}
	CANCEL_PROMPT_CALLBACK_EMPTY_VALUE = func() {}
)

// Describes available event reducer store values.
const (
	EVENT_NAME_EMPTY_VALUE      = ""
	EVENT_NAME_TOXIC_RAIN_VALUE = "toxic_rain"
	EVENT_STARTED_FALSE_VALUE   = "false"
	EVENT_STARTED_TRUE_VALUE    = "true"
	EVENT_ENDING_FALSE_VALUE    = "false"
	EVENT_ENDING_TRUE_VALUE     = "true"
)

// Describes available sound reducer store values.
const (
	SOUND_MUSIC_UPDATED_FALSE_VALUE = "false"
	SOUND_MUSIC_UPDATED_TRUE_VALUE  = "true"
)

// Describes available statistics reducer store values.
const (
	CONTENT_PING_STATISTICS_EMPTY_VALUE  = int64(0)
	METADATA_PING_STATISTICS_EMPTY_VALUE = int64(0)
)

// Describes available metadata reducer store values.
const (
	SELECTED_SESSION_METADATA_EMPTY_VALUE              = ""
	SELECTED_LOBBY_SET_UNIT_METADATA_EMPTY_VALUE       = ""
	SESSION_ALREADY_STARTED_METADATA_STATE_TRUE_VALUE  = "true"
	SESSION_ALREADY_STARTED_METADATA_STATE_FALSE_VALUE = "false"
)

var (
	RETRIEVED_SESSIONS_METADATA_EMPTY_VALUE  = []interface{}{}
	RETRIEVED_LOBBY_SET_METADATA_EMPTY_VALUE = []interface{}{}
)

// Describes available session reducer store values.
const (
	RESET_SESSION_FALSE_VALUE  = "false"
	RESET_SESSION_TRUE_VALUE   = "true"
	STATIC_SESSION_EMPTY_VALUE = false
)

var (
	POSITION_SESSION_EMPTY_VALUE          dto.Position
	STAGE_POSITION_SESSION_EMPTY_VALUE    dto.Position
	PREVIOUS_POSITION_SESSION_EMPTY_VALUE dto.Position
	RETRIEVED_USERS_METADATA_EMPTY_VALUE  dto.RetrievedUsersMetadataSessionSet = make(dto.RetrievedUsersMetadataSessionSet)
	RETRIEVED_CHESTS_EMPTY_VALUE          dto.RetrievedChests
	RETRIEVED_HEALTH_PACKS_EMPTY_VALUE    dto.RetrievedHealthPack
	INVENTORY_OPENED_FALSE_VALUE                                     = "false"
	INVENTORY_OPENED_TRUE_VALUE                                      = "true"
	CHEST_OPENED_FALSE_VALUE                                         = "false"
	CHEST_OPENED_TRUE_VALUE                                          = "true"
	SELECTED_POSITION_EMPTY_VALUE         *dto.SelectedObjectDetails = nil
)

// Describes available collections reducer store values.
const (
	RESET_COLLECTIONS_FALSE_VALUE = "false"
	RESET_COLLECTIONS_TRUE_VALUE  = "true"
)

// Describes available travel reducer store values.
const (
	RESET_TRAVEL_FALSE_VALUE = "false"
	RESET_TRAVEL_TRUE_VALUE  = "true"

	START_SESSION_TRAVEL_FALSE_VALUE = "false"
	START_SESSION_TRAVEL_TRUE_VALUE  = "true"
)

// Describes available death reducer store values.
const (
	RESET_DEATH_FALSE_VALUE = "false"
	RESET_DEATH_TRUE_VALUE  = "true"
)
