// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/content/content.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents common position message.
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int64                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int64                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_api_content_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Represents users positions retrieval request message.
type GetUserPositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPositionsRequest) Reset() {
	*x = GetUserPositionsRequest{}
	mi := &file_api_content_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPositionsRequest) ProtoMessage() {}

func (x *GetUserPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPositionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPositionsRequest) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserPositionsRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *GetUserPositionsRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

// Represents users positions retrieval response message.
type GetUserPositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Position            `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPositionsResponse) Reset() {
	*x = GetUserPositionsResponse{}
	mi := &file_api_content_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPositionsResponse) ProtoMessage() {}

func (x *GetUserPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPositionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPositionsResponse) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserPositionsResponse) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

// Represents users metadata retrieval request message.
type GetUserMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserMetadataRequest) Reset() {
	*x = GetUserMetadataRequest{}
	mi := &file_api_content_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMetadataRequest) ProtoMessage() {}

func (x *GetUserMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetUserMetadataRequest) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserMetadataRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *GetUserMetadataRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

// Represents common metadata message.
type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Skin          string                 `protobuf:"bytes,2,opt,name=skin,proto3" json:"skin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_api_content_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{4}
}

func (x *Metadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metadata) GetSkin() string {
	if x != nil {
		return x.Skin
	}
	return ""
}

// Represents users positions retrieval response message.
type GetUserMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      []*Metadata            `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserMetadataResponse) Reset() {
	*x = GetUserMetadataResponse{}
	mi := &file_api_content_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMetadataResponse) ProtoMessage() {}

func (x *GetUserMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetUserMetadataResponse) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserMetadataResponse) GetMetadata() []*Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_api_content_content_proto protoreflect.FileDescriptor

const file_api_content_content_proto_rawDesc = "" +
	"\n" +
	"\x19api/content/content.proto\x12\acontent\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x03R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x03R\x01y\"K\n" +
	"\x17GetUserPositionsRequest\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\"K\n" +
	"\x18GetUserPositionsResponse\x12/\n" +
	"\tpositions\x18\x01 \x03(\v2\x11.content.PositionR\tpositions\"J\n" +
	"\x16GetUserMetadataRequest\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\".\n" +
	"\bMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04skin\x18\x02 \x01(\tR\x04skin\"H\n" +
	"\x17GetUserMetadataResponse\x12-\n" +
	"\bmetadata\x18\x01 \x03(\v2\x11.content.MetadataR\bmetadataBEZCgithub.com/YarikRevich/fate-seekers/pkg/core/networking/content/apib\x06proto3"

var (
	file_api_content_content_proto_rawDescOnce sync.Once
	file_api_content_content_proto_rawDescData []byte
)

func file_api_content_content_proto_rawDescGZIP() []byte {
	file_api_content_content_proto_rawDescOnce.Do(func() {
		file_api_content_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_content_content_proto_rawDesc), len(file_api_content_content_proto_rawDesc)))
	})
	return file_api_content_content_proto_rawDescData
}

var file_api_content_content_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_content_content_proto_goTypes = []any{
	(*Position)(nil),                 // 0: content.Position
	(*GetUserPositionsRequest)(nil),  // 1: content.GetUserPositionsRequest
	(*GetUserPositionsResponse)(nil), // 2: content.GetUserPositionsResponse
	(*GetUserMetadataRequest)(nil),   // 3: content.GetUserMetadataRequest
	(*Metadata)(nil),                 // 4: content.Metadata
	(*GetUserMetadataResponse)(nil),  // 5: content.GetUserMetadataResponse
}
var file_api_content_content_proto_depIdxs = []int32{
	0, // 0: content.GetUserPositionsResponse.positions:type_name -> content.Position
	4, // 1: content.GetUserMetadataResponse.metadata:type_name -> content.Metadata
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_content_content_proto_init() }
func file_api_content_content_proto_init() {
	if File_api_content_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_content_content_proto_rawDesc), len(file_api_content_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_content_content_proto_goTypes,
		DependencyIndexes: file_api_content_content_proto_depIdxs,
		MessageInfos:      file_api_content_content_proto_msgTypes,
	}.Build()
	File_api_content_content_proto = out.File
	file_api_content_content_proto_goTypes = nil
	file_api_content_content_proto_depIdxs = nil
}
